---
title: "MJOLNIR_AMBI_DescriptiveAnalysis"
author: "Léo HENRY"
date: "4/20/2022"
output: html_document
---

# Packages

```{r}
library(questionr)
library(FactoMineR)
library(tidyverse)
library(psych)
library(GPArotation)
library(AMBI)
options(max.print=5000)
```

# data

```{r}
df <- read.csv("./data/mjolnir_clean_v3_1_DemoVarText.csv")
```


# Calculation of the AMBI


```{r}
df_2 <- calculate_AMBI(df, var_name = "aliases")
df_2 %>% select(matches("^AMBI_MSR"))
```


```{r}
write.csv(df_2,"./data/mjolnir_clean_v4_AMBI_msr.csv")
rm(df, df_2)
```

# EFA

```{r}
df <- read.csv("./data/mjolnir_clean_v4_AMBI_msr.csv")
```

## Parallel analysis

```{r}
parallel <- fa.parallel(df[,c(colnames(df) %>% str_detect("^AMBI_MSR_") %>% which)],
                        fm = "minres", fa = "fa")
```

```{r}
parallel$nfact
```


According to the parallel analysis we should have 18 factors.

## Factor Analysis

```{r}
df_ambi_cor <- df[,c(colnames(df) %>% str_detect("^AMBI_MSR_") %>% which)] %>% cor() 
```


```{r}
res <- fa(r = df_ambi_cor, scores = "tenBerge",
           nfactors = parallel$nfact, rotate= "bentlerT", fm="uls")
res
```

```{r}
f_EFA_testsimple <- function(loadings, cutoff){
  res <- list()
  res$v_load_nbfactor <- rowSums(abs(loadings)>cutoff)
  # we want these values to be the minimum possible
  res$n_load_nb <- (res$v_load_nbfactor!=1) %>% sum()
  res$n_load_perc <- round(res$n_load_nb/length(res$v_load_nbfactor),2)
  
  res$v_factor_nbload <- colSums(abs(loadings)>cutoff)
  # we want these values to be the minimum possible
  res$n_factor_nb <- (res$v_factor_nbload==0) %>% sum()
  res$n_factor_perc <- round(res$n_factor_nb/length(res$v_factor_nbload),2)
  cat(paste0("\nNb Factors: ", ncol(loadings), " | Cutoff: ", cutoff,
               "\n    - Loadings not simple: ", res$n_load_nb, " | ", res$n_load_perc,
               "\n    - Factors not simple:  ", res$n_factor_nb, " | ", res$n_factor_perc))
  return(res)
}
```

```{r}
test <- map(seq(5,30,1),
            function(y){
              res.efa <- fa(r = df_ambi_cor, scores = "tenBerge",
                   nfactors = y, rotate= "bentlerT", fm="uls")
              res.f <- map(seq(0.1, 0.9, 0.1),
                           function(x){
                              r <- f_EFA_testsimple(res.efa$loadings, x)
                              res <- (r$n_factor_perc + r$n_load_perc)/2
                              return(res)
                            }) %>% as_vector
              return(res.f)
            })
```


```{r}
names(test) <- seq(5,30,1)
df_test <- test %>% as_tibble()
row.names(df_test) <- seq(0.1,0.9,0.1)
map(df_test, function(x){c(min(x), (x==min(x)) %>% which())})
```

```{r}
map(df_test, function(x){c(min(x), (x==min(x)) %>% which())}) %>% as_vector %>% min()
```

```{r}
res <- fa(r = df_ambi_cor, scores = "tenBerge",
           nfactors = 13, rotate= "bentlerT", fm="uls")
res
```

RMSR = 0.03

```{r}
test <- f_EFA_testsimple(res$loadings,0.5)
```


```{r}
rownames(res$loadings) <- rownames(res$loadings) %>% str_remove("^AMBI_MSR_[0-9]{1,}_")
print(res$loadings,cutoff = 0.5)
```

```{r}

l_helpunderstandingfactors <- map(seq(1,ncol(res$loadings),1), function(x){
  
  ch_neg <- res$loadings[(abs(res$loadings[,x])>0.5)%>%which,x] %>% {.<0} %>% which() %>% 
    names() %>% str_remove('^[0-9]{1,3}_[A-Z.]{1,}_') %>% paste0(.,collapse = ", ") %>% paste0("    - Negative: ", .)
  ch_pos <- res$loadings[(abs(res$loadings[,x])>0.5)%>%which,x] %>% {.>0} %>% which() %>% 
    names() %>% str_remove('^[0-9]{1,3}_[A-Z.]{1,}_') %>% paste0(.,collapse = ", ") %>% paste0("    - Positive: ", .)
  
  ch_res <- paste0(colnames(res$loadings)[x], "\n", ch_neg, "\n", ch_pos, "\n", "\n")
  
  cat(ch_res)
  
  return(ch_res)
})

```


```{r}
print(res)
```

```{r}
res_df <- factor.scores(df[,c(colnames(df) %>% str_detect("^AMBI_MSR_") %>% which)], res, Phi = NULL,
                        method = "tenBerge",
                        impute = "none")
colnames(res_df$scores) <- paste0("AMBI_MSR_EFA_", colnames(res_df$scores))
df_2 <- cbind(df, res_df$scores)
```

## Saving

```{r}
write.csv(df_2,"./data/mjolnir_clean_v4_1_AMBI_EFA.csv")
rm(df, df_2, df_ambi_cor, df_test, parallel, res, res_df, test, l_helpunderstandingfactors, cutoff, t, f_EFA_testsimple)
```

# Descriptive EFA and Demo

```{r}
df <- read.csv("./data/mjolnir_clean_v4_1_AMBI_EFA.csv")
```

## EFA

```{r}
options(scipen=999)
map(df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which,
    function(x){summary(df[,x])})
```

```{r}
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=EXPGRP_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=CONTINENT_BORN_TEXT_3)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=HAS_LIVED_USA)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, x= CONTINENT_BORN_TEXT_3, fill=EXPGRP_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df$HH_INCOME_TEXT <- fct_recode(df$HH_INCOME %>% as.character,
"Less than $10,000"="1",
"$10,000 to $30,000"="2",
"$30,000 to $50,000"="3",
"$50,000 to $70,000"="4",
"$70,000 to $100,000"="5",
"$100,000 to $200,000"="6",
"$200,000 to $500,000"="7",
"$500,000 or more"="8")
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=HH_INCOME_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df$EDUCATION_1_TEXT <- fct_recode(df$EDUCATION_1 %>% as.character,
          "Less than high school degree"="1",
          "High school graduate"="2",
          "Some college but no degree"="3",
          "Associate degree in college"="4",
          "Bachelor's degree in college"="5",
          "Master's degree"="6",
          "Doctoral degree"="7",
          "Professional degree (JD, MD)"="8")
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=EDUCATION_1_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

```{r}
df$EDUCATION_1_TEXT <- fct_recode(df$EDUCATION_1 %>% as.character,
          "Less than high school degree"="1",
          "High school graduate"="2",
          "Some college but no degree"="3",
          "Associate degree in college"="4",
          "Bachelor's degree in college"="5",
          "Master's degree"="6",
          "Doctoral degree"="7",
          "Professional degree (JD, MD)"="8")
df %>% 
  gather(key = "AMBI_EFA_var", value="AMBI_EFA_res", df %>% colnames %>% str_detect("^AMBI_MSR_EFA_") %>% which) %>%
  ggplot(., aes(y=AMBI_EFA_res, fill=EDUCATION_1_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_EFA_var, ncol = 5)
```

# Save Packages

































