---
title: "vignettes"
output: html_document
date: '2022-05-19'
---

```{r setup, include=FALSE}
df <- read.csv("./data/mjolnir_clean_v6_Covmis.csv")
df$ID <- seq(1:nrow(df))
```

```{r}
d <- df %>% select(ID, matches("^V"))
```

```{r}
d %>% select(matches("^V[1-4].[12]_[A-Z]_JudgeOther_1")) %>% colnames() %>% str_remove("JudgeOther_1$")
d %>% select(matches("^V1.1_C_Judge(Other|Self)_[0-9]$")) %>% colnames() %>% str_remove("^V1.1_C_")
d %>% select(matches("^V[1-4].[0-9](_[A-Z]|)_JudgeOther_1")) %>% colnames()
d %>% select(matches("^V[1-4].[0-9](_[W]|)_Judge(Other|Self)_[0-9]$")) %>% colnames() %>% str_remove("^V[1-4].[0-9](_[A-Z]|)_") %>% as_factor() %>% levels()

```

```{r}
dt <- map(d %>% select(matches("^V[1-4].[0-9](_[A-Z]|)_JudgeOther_1")) %>% colnames() %>% str_remove("JudgeOther_1$"), function(i){c
    v_names <- paste0(i, d %>% select(matches(paste0(i,"Judge(Other|Self)_[0-9]$"))) %>% colnames() %>% str_remove(i))
    d_res <- unite(d[,v_names], col=v_col_name, sep=">>>", remove=T)
    return(d_res)
  }) %>% 
  purrr::transpose() %>% 
  map(bind_cols)
dt <- dt[[1]]
colnames(dt) <- paste0(d %>% select(matches("^V[1-4].[0-9](_[A-Z]|)_JudgeOther_1")) %>% colnames() %>% str_remove("JudgeOther_1$"),"aggregate")
df <- cbind(d, dt)
dt
```


```{r}
test <- d %>%
  gather(vignette_name, vignette_result, d %>% colnames() %>% str_detect("^V[1-4].[0-9](_[A-Z]|)_Judge(Other|Self)_[0-9]$") %>% which()) %>%
  filter(!(is.na(vignette_result))) %>%
  mutate(V_Number=vignette_name %>% str_extract("[0-9]"),
         V_racename=vignette_name %>% str_extract("[WIBC]"),
         V_update=vignette_name %>% str_detect("^V[0-9].2"),
         V_question=vignette_name %>% str_extract("Judge(Other|Self)_[0-9]$"))
test
```

```{r}
test %>% select(vignette_name) %>% as.vector() %>% str_detect("^V1.[12]_[A-Z]_")
test$vignette_name %>% str_extract("[WIBC]") %>% freq()

test$vignette_name %>% str_extract("Judge(Other|Self)_[0-9]$") %>% freq()
```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```

```{r}

```


```{r}

```































