---
title: "MJOLNIR_BIG5_DescriptiveAnalysis"
author: "Léo HENRY"
date: "4/19/2022"
output: html_document
---

# Packages

```{r}
library(questionr)
library(FactoMineR)
library(tidyverse)
library(lavaan)
library(semTools)
library(lavaanPlot)
library(MVN)
library(MIIVsem)
options(max.print=2000)
```
# SEM on the big 5

## Data

```{r}
df <- read.csv('./data/mjolnir_clean_v4_1_AMBI_EFA.csv')
```

## SEM

```{r}
model <- '
Neuroticism =~ AMBI_MSR_1_NEOPIR_ANXIETY + AMBI_MSR_2_NEOPIR_ANGRYHOSTILITY + AMBI_MSR_3_NEOPIR_DEPRESSION + AMBI_MSR_4_NEOPIR_SELFCONSCIOUSNESS + AMBI_MSR_5_NEOPIR_IMPULSIVENESS + AMBI_MSR_6_NEOPIR_VULNERABILITY
Extraversion =~ AMBI_MSR_7_NEOPIR_WARMTH + AMBI_MSR_8_NEOPIR_GREGARIOUSNESS + AMBI_MSR_9_NEOPIR_ASSERTIVENESS + AMBI_MSR_10_NEOPIR_ACTIVITY + AMBI_MSR_11_NEOPIR_EXCITEMENTSEEKING + AMBI_MSR_12_NEOPIR_POSITIVEEMOTIONS
Openness =~ AMBI_MSR_13_NEOPIR_FANTASY + AMBI_MSR_14_NEOPIR_AESTHETICS + AMBI_MSR_15_NEOPIR_FEELINGS + AMBI_MSR_16_NEOPIR_ACTIONS + AMBI_MSR_17_NEOPIR_IDEAS + AMBI_MSR_18_NEOPIR_VALUES
Agreeableness =~ AMBI_MSR_19_NEOPIR_TRUST+AMBI_MSR_20_NEOPIR_STRAIGHTFORWARDNESS+AMBI_MSR_21_NEOPIR_ALTRUISM+AMBI_MSR_22_NEOPIR_COMPLIANCE+AMBI_MSR_23_NEOPIR_MODESTY+AMBI_MSR_24_NEOPIR_TENDERMINDEDNESS
Conscientiousness =~ AMBI_MSR_25_NEOPIR_COMPETENCE+AMBI_MSR_26_NEOPIR_ORDER+AMBI_MSR_27_NEOPIR_DUTIFULNESS+AMBI_MSR_28_NEOPIR_ACHIEVEMENTSTRIVING+AMBI_MSR_29_NEOPIR_SELFDISCIPLINE+AMBI_MSR_30_NEOPIR_DELIBERATION
'
```

```{r}
fit <- cfa(model, data = df, estimator = "ML")
```

```{r}
summary(fit, fit.measures=T, standardized=T, rsquare=T) 
```

```{r}
reliability(fit)
```

```{r}
modindices(fit) %>% arrange(-mi) %>% head(20)
```


```{r}
#semPlot::semPaths(fit, "std", rotation = 2)
```

## Scoring the big 5 with SEM result

```{r}
f_semscoring_latent <- function(fit, data, scaled = TRUE){
  
  df_sem_estimate <- fit %>% lavaan::partable() %>% as_tibble %>% filter(user==1)
  v_latent_var <- df_sem_estimate$lhs %>% as_factor %>% levels
  
  f_calculate_latent <- function(latent_var){
    
    v_obs_var <- df_sem_estimate %>% filter(lhs==latent_var) %>% select(rhs) %>% as_vector()
    
    f_calculate_obs <- function(obs_var){
    
      res <- scale(data[,obs_var]) * (df_sem_estimate %>% filter(lhs==latent_var, rhs==obs_var) %>% select(est) %>% as_vector())
      return(res)
    }
    
    res <- map(v_obs_var, function(x){f_calculate_obs(x)}) %>% as_tibble %>% rowSums
    if(scaled) res <- res %>% scale
    return(res)
  }
  
  res <- map(v_latent_var,function(x){f_calculate_latent(x)}) %>% as.data.frame
  colnames(res) <- v_latent_var
  return(res)
}
```

```{r}
df_score_big5 <- f_semscoring_latent(fit, df, scaled = TRUE)
df_score_big5
```

```{r}
colnames(df_score_big5) <- paste0("AMBI_BIG5_", colnames(df_score_big5))
df <- cbind(df, df_score_big5)
```

```{r}
write.csv(df,"./data/mjolnir_clean_v5_AMBI_BIG5.csv")
```


# Descriptive analysis of the big 5

## Data

```{r}
df <- read.csv(file = "./data/mjolnir_clean_v5_AMBI_BIG5.csv")
```


## Univaried analysis

```{r}
map(df[,c(colnames(df) %>% str_detect("^AMBI_BIG5_") %>% which)], function(x){summary(x)})
```

## Bivaried analysis

```{r}
v_big5 <- c("AMBI_BIG5_Neuroticism", "AMBI_BIG5_Extraversion", 
               "AMBI_BIG5_Openness", "AMBI_BIG5_Agreeableness",
               "AMBI_BIG5_Conscientiousness")

pairs(df[, v_big5])

df_big5_pairs <- combn(v_big5, 2) %>% as_tibble()

map(seq(1,df_big5_pairs %>% length()), 
    function(x){
      r <- cor(df[,df_big5_pairs[1,x] %>% as.character()],
               df[,df_big5_pairs[2,x] %>% as.character()])
      print(paste0(df_big5_pairs[1,x], " X ", df_big5_pairs[2,x],":  ",round(r,2)))
      return()
          })
```

# Boxplot

```{r}
df %>% 
  gather(key = "AMBI_BIG5_var", value="AMBI_BIG5_res", df %>% colnames %>% str_detect("^AMBI_BIG5_") %>% which) %>%
  ggplot(., aes(y=AMBI_BIG5_res, fill=EXPGRP_TEXT)) +
  geom_boxplot() +
  facet_wrap(~ AMBI_BIG5_var)
colnames(df)[colnames(df) %>% str_detect("^AMBI_BIG5_")] 
lt <- map(colnames(df)[colnames(df) %>% str_detect("^AMBI_BIG5_")],
    function(x){
      drun <- data_frame(values = df[,x],
                         race = df$EXPGRP_TEXT %>% as.factor())
      res <- list()
      res[["nom"]] <- x
      res[["aov"]] <- drun %>% rstatix::anova_test(values ~ race)
      pwc <- drun %>% rstatix::tukey_hsd(values ~ race)
      res[["pwc"]] <- pwc
      res[["drun"]] <- drun
      pwc <- res[["pwc"]] %>% rstatix::add_xy_position(x = "race")
      res[["bbplot"]] <- ggpubr::ggboxplot(res[["drun"]], x = "race", y = "values") +
        ggpubr::stat_pvalue_manual(pwc, hide.ns = TRUE) +
        labs(subtitle = rstatix::get_test_label(res[["aov"]], detailed = TRUE),
             caption = rstatix::get_pwc_label(pwc),
             title = x)
      return(res)})


ggpubr::ggarrange(plotlist=lt, labels = c('A', 'B', 'C', 'D', 'E'), nrow = 2, ncol=3)

```



## Multivaried analysis

```{r}
res.pca <- PCA(df[,c(colnames(df) %>% str_detect("^AMBI_BIG5_") %>% which)], 
               quali.sup = df[,c(colnames(df) %>% str_detect("^AMBI_BIG5_") %>% which)],
               scale.unit=TRUE, ncp=25, graph=T)
```













